"""
Django settings for WallPaper project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import datetime
from pathlib import Path
from django.utils.translation import gettext_noop

BASE_DIR = Path(__file__).resolve().parent.parent
# =======国际化=============================
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True

LANGUAGES = [
    ('es', gettext_noop('Spanish')),        # 1、西班牙语（可选扩展）.
    ('en', gettext_noop('English')),        # 2、英语 .
    ('pt', gettext_noop('Portuguese')),     # 3、葡萄牙语（葡萄牙） .
    ('ja', gettext_noop('Japanese')),       # 4、日语 .
    ('ko', gettext_noop('Korean')),         # 5、韩语 .
    ('zh-hans', gettext_noop('Simplified Chinese')),  # 6、简体中文.
    ('zh-hant', gettext_noop('Traditional Chinese')), # 繁体中文（可选）
    ('de', gettext_noop('German')),                   # 德语
    ('fr', gettext_noop('French')),                   # 法语（可选扩展）
]
LOCALE_PATHS = [
    os.path.join(BASE_DIR.parent, 'locale'),
]

SECRET_KEY = 'django-insecure-)my3+p2r5=0oesi&+wa#2rt9q66ph7l1(12tn%kr$z03qd6_^c'

DEBUG = True
ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
LOG_DIR = BASE_DIR.parent / 'logs'
CurrentDayLog = LOG_DIR / str(datetime.now())[:10]
RESOURCE_DIR = BASE_DIR.parent / 'resource'
FONT_DIR = RESOURCE_DIR / 'font'
IMAGE_DIR = RESOURCE_DIR / 'image'
SIGN_DIR = RESOURCE_DIR / 'sign'
KEY_DIR = RESOURCE_DIR / 'key'
DOWNLOAD_DIR = RESOURCE_DIR / 'downloads'
if not KEY_DIR.exists():
    KEY_DIR.mkdir()
if not LOG_DIR.exists():
    LOG_DIR.mkdir()
if not CurrentDayLog.exists():
    CurrentDayLog.mkdir()
if not RESOURCE_DIR.exists():
    RESOURCE_DIR.mkdir()
if not FONT_DIR.exists():
    FONT_DIR.mkdir()
if not IMAGE_DIR.exists():
    IMAGE_DIR.mkdir()
if not DOWNLOAD_DIR.exists():
    DOWNLOAD_DIR.mkdir()

INSTALLED_APPS = [
    "App",
    "models",
    'rest_framework',
    'drf_spectacular',
    'django_apscheduler',
]
APSCHEDULER_TIMEZONE = TIME_ZONE

MIDDLEWARE = [
    'tool.middleware.IPLogMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WallPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'tool.authentication.TokenAuthentication',
        'tool.authentication.CustomBasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [

        # 'tool.permissions.IsTokenValid',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'UNAUTHENTICATED_USER': None

}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Crashcheck 账户管理 API',
    'DESCRIPTION': '简化版后端接口文档（中文）',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

WSGI_APPLICATION = 'WallPaper.wsgi.application'
DATABASE_ROUTERS = ['WallPaper.settings.db_router.AppDBRouter']
POSTGRES_HOST_OLD = "119.45.233.147"  # 老库（只读）
POSTGRES_HOST_NEW = "101.32.179.223"  # 新库（默认库，可写）

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'wallpaper_db',
        'USER': 'wallpaper123',
        'PASSWORD': 'wallpaper123',
        'HOST': POSTGRES_HOST_NEW,
        'PORT': '5436',
        'OPTIONS': {
            'connect_timeout': 10,
        },
    },
    'old_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crash_db',
        'USER': 'crash',
        'PASSWORD': 'crash',
        'HOST': POSTGRES_HOST_OLD,
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
                      '[%(levelname)s][%(message)s]'
        },
        'simple': {
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d]%(message)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'info': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': CurrentDayLog / f'{str(datetime.now())[:10]}_info.log',
            'maxBytes': 1024 * 1024 * 50,
            'backupCount': 3,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': CurrentDayLog / f'{str(datetime.now())[:10]}_error.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        }
    },
    'loggers': {
        '': {
            'handlers': ['info', 'console', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'collect': {
            'handlers': ['console', ],
            'level': 'INFO',
        }
    },
}