# Generated by Django 5.2.6 on 2026-03-03 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=256)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("admin", "管理员"),
                            ("operator", "操作员"),
                        ],
                        default="operator",
                        max_length=20,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "后台管理员",
                "verbose_name_plural": "后台管理员",
                "db_table": "c_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="用户OpenID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "user_avatar",
                    models.TextField(blank=True, null=True, verbose_name="用户头像"),
                ),
                (
                    "user_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "男"), ("female", "女"), ("unknown", "未知")],
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "user_telphone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="是否为VIP"),
                ),
                (
                    "vip_type",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "月付"), ("once", "单次")],
                        max_length=20,
                        null=True,
                        verbose_name="VIP类型",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "share_success_count",
                    models.PositiveIntegerField(default=0, verbose_name="分享成功次数"),
                ),
                (
                    "allow_count",
                    models.PositiveIntegerField(default=0, verbose_name="允许使用次数"),
                ),
                (
                    "fail_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败次数"),
                ),
                (
                    "vip_expire_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="VIP到期日"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "正常"), (1, "冻结"), (2, "注销"), (3, "注销中")],
                        default=0,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="平台"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已注销"),
                ),
                (
                    "delete_requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="注销请求时间"
                    ),
                ),
                (
                    "deletion_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="注销截止时间（7天后）"
                    ),
                ),
            ],
            options={
                "verbose_name": "微信用户",
                "verbose_name_plural": "微信用户",
                "db_table": "wx_wechat_user",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "product_type",
                    models.CharField(max_length=20, verbose_name="商品类型"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品售价"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_sale", "上架销售"),
                            ("off_sale", "下架"),
                            ("out_of_stock", "缺货"),
                            ("pre_sale", "预售"),
                            ("discontinued", "已停产"),
                        ],
                        default="off_sale",
                        max_length=20,
                        verbose_name="商品状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("logo_url", models.CharField(verbose_name="商品主图URL")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="商品描述"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="商品编号"),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("days", models.IntegerField(default=0, verbose_name="充值天数")),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="地区区域"
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "wx_product",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(
                        fields=["product_type", "status"],
                        name="wx_product_product_df3e70_idx",
                    ),
                    models.Index(
                        fields=["created_time"], name="wx_product_created_4086a6_idx"
                    ),
                    models.Index(
                        fields=["is_recommended"], name="wx_product_is_reco_44d0c0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="配置名称", max_length=100),
                ),
                (
                    "provider",
                    models.CharField(blank=True, help_text="厂商", max_length=32),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="模型名称/版本", max_length=100
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(blank=True, default=True, help_text="是否启用"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        blank=True, default=False, help_text="是否设为默认（全局唯一）"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True, default=0, help_text="优先级，数值越大优先"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="访问密钥，读取时应掩码", max_length=256
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, help_text="自定义 API Base URL（代理/Azure 场景）"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="区域（Azure 等需要）", max_length=50
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        blank=True,
                        help_text="API 版本（Azure/OpenAI 兼容接口）",
                        max_length=50,
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(
                        blank=True, help_text="组织/项目标识（可选）", max_length=100
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, help_text="创建时间", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, help_text="更新时间", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aiconfigs",
                        to="models.wechatuser",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "db_table": "wx_aiconfig",
                "ordering": ["-is_default", "-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeChatPayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="商户订单号（系统内部唯一）",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="微信支付订单号（微信返回，唯一）",
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="订单总金额",
                    ),
                ),
                (
                    "payer_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="用户实际支付金额",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        blank=True,
                        choices=[("CNY", "人民币")],
                        default="CNY",
                        max_length=16,
                        verbose_name="货币类型",
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="支付人OpenID"
                    ),
                ),
                (
                    "payer_account",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="付款账号（如银行卡尾号，微信返回）",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="商品名称（冗余）"
                    ),
                ),
                (
                    "mch_id",
                    models.CharField(blank=True, max_length=32, verbose_name="商户号"),
                ),
                (
                    "appid",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="小程序AppID"
                    ),
                ),
                (
                    "sub_mch_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="子商户号（服务商模式时使用）",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JSAPI", "小程序支付/公众号支付"),
                            ("NATIVE", "扫码支付"),
                            ("APP", "APP支付"),
                            ("MWEB", "H5支付"),
                            ("MICROPAY", "付款码支付"),
                        ],
                        max_length=16,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "trade_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESS", "支付成功"),
                            ("REFUND", "转入退款"),
                            ("NOTPAY", "未支付"),
                            ("CLOSED", "已关闭"),
                            ("REVOKED", "已撤销（仅付款码支付）"),
                            ("USERPAYING", "用户支付中（仅付款码支付）"),
                            ("PAYERROR", "支付失败（仅付款码支付）"),
                        ],
                        default="NOTPAY",
                        max_length=32,
                        verbose_name="交易状态",
                    ),
                ),
                (
                    "bank_type",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="付款银行（如ICBC_DEBIT=工商银行借记卡）",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="订单创建时间"
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付完成时间（微信返回）"
                    ),
                ),
                (
                    "close_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="订单关闭时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="订单信息最后更新时间"
                    ),
                ),
                (
                    "notify_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="微信支付回调通知时间"
                    ),
                ),
                (
                    "is_notify_processed",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="是否已处理回调通知"
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="订单描述（传给微信的备注）",
                    ),
                ),
                (
                    "attach",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="附加数据（商户自定义，如订单来源）",
                    ),
                ),
                (
                    "posterId",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="海报ID"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="models.product",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_orders",
                        to="models.wechatuser",
                        verbose_name="支付人",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信支付订单",
                "verbose_name_plural": "微信支付订单",
                "db_table": "wx_order",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(
                        fields=["out_trade_no"], name="wx_order_out_tra_228a91_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="wx_order_transac_0d12d1_idx"
                    ),
                    models.Index(
                        fields=["payer", "trade_state"],
                        name="wx_order_payer_i_6e3356_idx",
                    ),
                    models.Index(
                        fields=["created_time"], name="wx_order_created_a40ee7_idx"
                    ),
                    models.Index(
                        fields=["trade_state", "created_time"],
                        name="wx_order_trade_s_aab239_idx",
                    ),
                ],
            },
        ),
    ]
