services:
  django_web:
    build:
      context: .
      cache_from:
        - wallpaper_backend-django_web:latest
    container_name: wallpaper_django_overseas
    restart: always


    env_file:
      - .env
    volumes:

      - ./media:/app/media
      - ./logs:/app/logs
      - ./resource:/app/resource
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: wallpaper_nginx_overseas
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/usr/share/nginx/html/static:ro
      # ✅ 挂载两个前端文件夹
      - ./page/markwallpapers:/usr/share/nginx/html/markwallpapers:ro
      - ./page/enhance:/usr/share/nginx/html/enhance:ro
    depends_on:
      - django_web
    networks:
      - app_network

networks:
  app_network: