FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY req.txt .

# 清华镜像源加速安装依赖，虚拟环境放在 /venv
RUN python -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r req.txt